#!/bin/bash
rm -rf ./$1
mkdir ./$1
now=0
for f in $@ 
do
	((now++))
	if [ $now -lt 3 ]
	then
		continue
	fi
	LIST=$(find . -name *.$f)
	for file in $LIST
	do 
		if [ $file == $1 -o $file == script ]
		then
			continue
		fi
		#echo ./$1/$(basename $file)
		base=$(basename $file)
		if [ -f ./$1/$base ]
		then
			now=1
			while [ -f ./$1/$base'('$now')' ]
			do
				now+=1
			done
			#echo $file1
			file1=./$1/$base'('$now')'
			cp -r $file $file1
		else
			cp -r $file ./$1
		fi
	done
done
tar -cf $2.tar $1 
echo done